### PR TITLE
ci: Add validation for more macOS and netcore versions

### PR DESCRIPTION
**Pull request by jeromelaban**
This PR adds an extended validation matrix to ensure msbuild extras work with a wider range of .NET Core and macOS versions.

### CODE REVIEW

**Comment by jeromelaban** [comment]
And it looks like there's an issue with netcore 3.1 on linux specifically (most likely to happen on macOS as well if .NET Core 3.1 gets the default): https://dev.azure.com/clairernovotny/GitBuilds/_build/results?buildId=3438&view=logs&j=a3deec3d-20d7-5d79-2090-7e19368c4709&t=cfff7be9-a121-5ebd-a90b-8bb7e69a46ab

@clairernovotny Do you know about this file ?

**Comment by clairernovotny** [comment]
No idea, can you file an issue on the main dotnet repos?

**Comment by jeromelaban** [comment]
Will do. I'll remove 3.1 from the matrix and create a new PR with just that to enable it.

**Comment by jeromelaban** [comment]
There it is https://github.com/dotnet/runtime/issues/34435

**Comment by clairernovotny** [comment]
Thanks!

**Pull request merged**
